### PR TITLE
18 fix project structure

### LINKED ISSUE #18: Add packages
Perhaps we could draw inspiration from [Jakarta2024](https://github.com/kappsegla/Jakarta2024) by incorporating well-organized packages. This would not only improve the overall project structure but also provide a clearer understanding of the necessary components for our project. What are your thoughts on this approach? 🤔

### PR DESCRIPTION
**Pull request by marcusju23**
Closes #18 and #15 .

### CODE REVIEW

**Review by TrungMa1 — COMMENTED** [review]
So this is Martin's structure that we are going to change after our own requests and build upon? Will this be like a base template for us?

**Comment by marcusju23** [comment]
> So this is Martin's structure that we are going to change after our own requests and build upon? Will this be like a base template for us?

Yeah we can just refactor names, add additional methods or functionality etc that we see fit with our project. Just address these things in future issues or PR's. I had to add the template files for me to be able to commit the packages 😵

**Comment by marcusju23** [comment]
> Structure looks nice, but please use movies where in Martins code he uses person since we decided to go with that :)

Yes of course, as I said earlier we can refactor that its just templates 😄 If you want I can add templates to the class names?

**Comment by TrungMa1** [comment]
Refactoring names and stuff could be done in a new issue, otherwise it feels like this PR would do too much. It would also close issue #16 if we do want to refactor the names in this PR

**Comment by BarbieQkiller** [comment]
> > Structure looks nice, but please use movies where in Martins code he uses person since we decided to go with that :)
> 
> Yes of course, as I said earlier we can refactor that its just templates 😄 If you want I can add templates to the class names?

Ah, my silly eyes skipped that comment ::D That is ok I guess, to do as you mentioned and make a new issue.

**Review by BarbieQkiller — APPROVED** [review]

**Review by BarbieQkiller — APPROVED** [review]
Great!  😄 

In the future I would love for all of us to (if possible) make smaller pull requests. This will hopefully make following all changes easier.

**Comment by marcusju23** [comment]
> Great!  😄 
> 
> In the future I would love for all of us to (if possible) make smaller pull requests. This will hopefully make following all changes easier.

I will keep that in mind.

**Review by TrungMa1 — APPROVED** [review]

**Pull request merged**
