### PR TITLE
Added function delete branch in pipeline

### LINKED ISSUE #44: [Update] - Remove branches after merging
Automating the process of removing branches after merging is not only convenient but also helps ensure consistency, reduces the risk of human error, and contributes to maintaining a clean and efficient version control system. To achieve this the CI pipeline has to be configured.

### PR DESCRIPTION
**Pull request by TrungMa1**
Hopefully this will automaticelly close finished branches

Closes #44

### CODE REVIEW

**Comment by BarbieQkiller** [comment]
Yay! Great 😄

**Review by BarbieQkiller — APPROVED** [review]
Nice!

**Review by Lucia560 — APPROVED** [review]
Superbra:)

**Review by marcusju23 — APPROVED** [review]
Great job! I can't find any issues. Approved! 👍

**Pull request merged**
