### PR TITLE
Movie exception mapper

### LINKED ISSUE #35: [Implement] - Exception mapper
Implementing an exception mapper in our application provides a structured and efficient way to handle errors, improving the overall quality and reliability of the software. It contributes to a better user experience and facilitates the development and maintenance of the application.

### PR DESCRIPTION
**Pull request by Rishad11**
Added the exception mapper for a couple of standard http responses aswell as test for each response.

Closes #35

### CODE REVIEW

**Comment by Rishad11** [comment]
Both pipeline and sonarcloud tests failed? Could this be because of a missing dependency?

**Review by BarbieQkiller — APPROVED** [review]
Sweet!
Nice and structured, an excellent base. 

Well done!

**Review by Lucia560 — APPROVED** [review]
It looks good. Great jobb!

**Review by TrungMa1 — APPROVED** [review]
Alot of good work here, Rishad! Great work, looks good.

**Pull request merged**
