### PR TITLE
28 implement moviedto and movies class

### LINKED ISSUE #28: [Implement] - MovieDTO and movies class
By using Data Transfer Objects (DTOs), we can segregate the process of transferring data between different layers of an application from the underlying business logic. This separation promotes a cleaner and more maintainable codebase by encapsulating data transfer concerns in dedicated DTO classes.

waiting for a merge on PR-crud-operations first.

### PR DESCRIPTION
**Pull request by marcusju23**
Closes #28 .

### CODE REVIEW

**Comment by marcusju23** [comment]
> ## [Quality Gate Failed](https://sonarcloud.io/dashboard?id=Lucia560_Jakarta_labb&pullRequest=39) **Quality Gate failed**
> 
> Failed conditions  [0.0% Coverage on New Code](https://sonarcloud.io/component_measures?id=Lucia560_Jakarta_labb&pullRequest=39&metric=new_coverage&view=list) (required ≥ 80%)
> 
> [See analysis details on SonarCloud](https://sonarcloud.io/dashboard?id=Lucia560_Jakarta_labb&pullRequest=39)

0% coverage??? Is it possible because the tests are in packages? 🤔

**Comment by marcusju23** [comment]
> ## [Quality Gate Failed](https://sonarcloud.io/dashboard?id=Lucia560_Jakarta_labb&pullRequest=39) **Quality Gate failed**
> 
> Failed conditions  [0.0% Coverage on New Code](https://sonarcloud.io/component_measures?id=Lucia560_Jakarta_labb&pullRequest=39&metric=new_coverage&view=list) (required ≥ 80%)
> 
> [See analysis details on SonarCloud](https://sonarcloud.io/dashboard?id=Lucia560_Jakarta_labb&pullRequest=39)

a9dce28b855d1f8ea709f1d874bb6042
Interesting.. something wrong with SonarCloud? 🙂

**Comment by TrungMa1** [comment]
Must be something wrong with Sonarcloud, your work looks exceptional. Great work!

**Review by TrungMa1 — APPROVED** [review]
I cant spot any wrongs. Approved!

**Review by Lucia560 — APPROVED** [review]
Very well done:)  The failure is due to testing . Is not covering 80% of the code we already have.

**Pull request merged**
